title: "Trần Đức Tân"
description: "Backend Developer | AI Enthusiast"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/

author:
  name   : "Trần Đức Tân"
  avatar : "/assets/images/avt.jpg"
  bio    : "Backend Developer. Loves AI & Open Source."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/tantran1011"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/tan-tran-duc-40bba7307/"

# Hiển thị navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/

# Kết nối CSS
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      custom_css: "/assets/css/custom.scss"
